# Generated by Django 2.0.2 on 2019-02-04 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuntes', '0002_auto_20190127_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='fecha_recordatorio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='contenido',
            field=models.TextField(blank=True, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='hora',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
