# Generated by Django 2.0.2 on 2019-02-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuntes', '0003_auto_20190204_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
