# Generated by Django 2.0.2 on 2019-03-05 19:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companias_telefonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('anotaciones', models.TextField(blank=True, max_length=250, null=True)),
                ('link_fotos', models.URLField(blank=True, null=True)),
                ('latitud', models.CharField(blank=True, max_length=25, null=True)),
                ('longitud', models.CharField(blank=True, max_length=25, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Eventos_User', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Eventos_Estados', to='rutas.Estados')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pilotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_lincencia', models.CharField(blank=True, max_length=25, null=True)),
                ('tipo', models.CharField(blank=True, max_length=2, null=True)),
                ('link_scan', models.URLField(blank=True, null=True)),
                ('dpi', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rentadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('agregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Rentadora_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ruta_Entregas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('completado', models.BooleanField(default=False)),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Rutas_Entrega', to='equipamientos.Equipamiento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_salida', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_entrada', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('anotaciones', models.TextField(blank=True, max_length=250, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Rutas_User', to=settings.AUTH_USER_MODEL)),
                ('piloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Rutas_Pilotos', to='rutas.Pilotos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Telefonos_Piloto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('pertenece_a', models.CharField(blank=True, max_length=50, null=True)),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_TelefonosPiloto_User', to=settings.AUTH_USER_MODEL)),
                ('piloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Telefonos_Piloto', to='rutas.Pilotos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Telefonos_Rentadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('pertenece_a', models.CharField(blank=True, max_length=50, null=True)),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Telefonos_User', to=settings.AUTH_USER_MODEL)),
                ('rentadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Telefonos_Rentadora', to='rutas.Rentadora')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('placa', models.CharField(blank=True, max_length=25, null=True)),
                ('combustible', models.CharField(blank=True, max_length=25, null=True)),
                ('fotos', models.URLField(blank=True, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('hora_recepcion', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('kilometraje_recibido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('hora_hora', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('kilometraje_devuelto', models.CharField(blank=True, max_length=50, null=True)),
                ('anotaciones', models.TextField(blank=True, max_length=250, null=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Vehiculo_Marca', to='rutas.Marcas')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Vehiculo_Modelo', to='rutas.Modelos')),
                ('quien_devuelve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_VehiculosDevuelve_User', to=settings.AUTH_USER_MODEL)),
                ('quien_recibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_VehiculosRecibe_User', to=settings.AUTH_USER_MODEL)),
                ('rentadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Vehiculo_Rentadora', to='rutas.Rentadora')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rutas',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Rutas_Vehiculo', to='rutas.Vehiculos'),
        ),
        migrations.AddField(
            model_name='ruta_entregas',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Ruta_Rutas', to='rutas.Rutas'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='ruta_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Eventos_RutaEntregas', to='rutas.Ruta_Entregas'),
        ),
    ]
