# Generated by Django 2.0.2 on 2019-01-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionindicadores',
            name='debe_mejorar',
            field=models.BooleanField(default=False),
        ),
    ]
