# Generated by Django 2.0.2 on 2019-01-15 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_auto_20190115_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionindicadores',
            name='calificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='indicadores.Calificacion'),
        ),
    ]
