# Generated by Django 2.0.2 on 2019-01-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_auto_20190115_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionindicadores',
            name='calificacion',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='indicadores.Calificacion'),
        ),
    ]
