# Generated by Django 2.0.2 on 2019-02-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_auto_20190119_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='rubrica',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
