# Generated by Django 2.0.2 on 2019-03-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0005_calificacion_rubrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_version_indicador', to='indicadores.Indicador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
