# Generated by Django 2.0.2 on 2019-03-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_auto_20190204_1119'),
        ('indicadores', '0006_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_indicador', to='indicadores.Indicador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='version',
            name='indicador',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.AddField(
            model_name='versionindicador',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_version_indicador', to='evaluaciones.Version'),
        ),
    ]
