# Generated by Django 2.0.2 on 2019-01-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_auto_20190115_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='porcentaje_penalizacion',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
