# Generated by Django 2.0.2 on 2019-02-04 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_auto_20190123_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
