# Generated by Django 2.0.2 on 2019-01-14 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlamadaAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, max_length=250, null=True)),
                ('penalizacion', models.BooleanField()),
                ('tiempo', models.CharField(blank=True, max_length=150, null=True)),
                ('compromiso', models.CharField(blank=True, max_length=150, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to=settings.AUTH_USER_MODEL)),
                ('levantada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levantada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
