# Generated by Django 2.0.2 on 2019-01-14 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0002_auto_20190113_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamadaatencion',
            name='levantada_por',
            field=models.ManyToManyField(blank=True, null=True, related_name='levantada', to=settings.AUTH_USER_MODEL),
        ),
    ]
