# Generated by Django 2.0.2 on 2019-01-14 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0003_auto_20190113_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamadaatencion',
            name='compromiso',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='llamadaatencion',
            name='levantada_por',
            field=models.ManyToManyField(blank=True, related_name='levantada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='llamadaatencion',
            name='motivo',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
