# Generated by Django 2.0.2 on 2019-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0005_auto_20190123_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamadaatencion',
            name='compromiso',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
