# Generated by Django 2.0.2 on 2019-03-13 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20190311_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacionesTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('apunte', models.TextField(blank=True, max_length=250, null=True)),
                ('fecha_hora_anotacion', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 9, 8, 11, 155690), null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='replanificaciones',
            name='tarea',
        ),
        migrations.AlterField(
            model_name='programaciones',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_hora_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_hora_planificada',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 9, 8, 11, 155190), null=True),
        ),
        migrations.DeleteModel(
            name='Replanificaciones',
        ),
        migrations.AddField(
            model_name='anotacionestarea',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_AnotacionesTarea_Tareas', to='tareas.Tareas'),
        ),
    ]
