# Generated by Django 2.0.2 on 2019-03-15 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_auto_20190313_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados',
            name='ponderacion',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='anotacionestarea',
            name='fecha_hora_anotacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 15, 11, 11, 18, 568346), null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_hora_planificada',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 15, 11, 11, 18, 567345), null=True),
        ),
    ]
