# Generated by Django 2.0.2 on 2019-03-15 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_auto_20190315_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='fecha_hora_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 15, 15, 57, 46, 602856), null=True),
        ),
        migrations.AlterField(
            model_name='anotacionestarea',
            name='fecha_hora_anotacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 15, 15, 57, 46, 603856), null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_hora_planificada',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 15, 15, 57, 46, 602856), null=True),
        ),
    ]
