# Generated by Django 2.0.2 on 2019-03-28 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_auto_20190315_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacionestarea',
            name='apunte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anotacionestarea',
            name='fecha_hora_anotacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 28, 11, 29, 25, 323194), null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='anotaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_hora_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 28, 11, 29, 25, 322194), null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_hora_planificada',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 28, 11, 29, 25, 322194), null=True),
        ),
    ]
