# Generated by Django 2.0.2 on 2019-05-31 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0016_auto_20190528_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacionestarea',
            name='fecha_hora_anotacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 31, 12, 10, 42, 815831), null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='tarea',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
