# Generated by Django 2.0.2 on 2019-06-05 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0018_auto_20190605_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacionestarea',
            name='fecha_hora_anotacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 5, 14, 44, 43, 68476), null=True),
        ),
    ]
