# Generated by Django 2.0.2 on 2019-06-20 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0020_auto_20190612_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacionestarea',
            name='fecha_hora_anotacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 13, 50, 51, 926831), null=True),
        ),
    ]
