# Generated by Django 2.0.2 on 2019-06-20 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0021_auto_20190620_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacionestarea',
            name='fecha_hora_anotacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 14, 40, 39, 163634), null=True),
        ),
    ]
