# Generated by Django 2.0.2 on 2019-08-23 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0024_auto_20190624_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacionestarea',
            name='fecha_hora_anotacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 23, 7, 47, 35, 322527), null=True),
        ),
    ]
