# Generated by Django 2.0.2 on 2019-06-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicotarima',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relHistoricoTarimaEstado', to='bodega.EstadoTarima'),
        ),
        migrations.AlterField(
            model_name='tarima',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relTarimaEstado', to='bodega.EstadoTarima'),
        ),
    ]
