# Generated by Django 2.0.2 on 2019-06-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_auto_20190620_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicotarima',
            old_name='creado_por',
            new_name='editado_por',
        ),
        migrations.RenameField(
            model_name='tarima',
            old_name='creado_por',
            new_name='editado_por',
        ),
        migrations.AlterField(
            model_name='historicotarima',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relHistoricoTarimaSector', to='bodega.Sector'),
        ),
        migrations.AlterField(
            model_name='historicotarima',
            name='tarima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relHistoricoTarimaTarima', to='bodega.Tarima'),
        ),
    ]
