# Generated by Django 2.0.2 on 2019-06-24 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_auto_20190624_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicotarima',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
