# Generated by Django 2.0.2 on 2019-08-23 13:47

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0004_historicotarima_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('no_entrada', models.PositiveSmallIntegerField(unique=True)),
                ('fecha_entrada', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('completado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControlTriageReimpresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('motivo_reimpresion', models.TextField(blank=True, null=True, verbose_name='Motivo de la Reimpresión')),
                ('fecha_reimpresion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('triage', models.PositiveSmallIntegerField()),
                ('fecha_entrega', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('firma_digital', models.BooleanField(default=False, verbose_name='Confirmar de recibido')),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relControlTriageReimpresosAutorizadoPor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DespachoTriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('rando_inicia', models.PositiveSmallIntegerField()),
                ('rando_termina', models.PositiveSmallIntegerField()),
                ('fecha_entrega', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('firma_digital', models.BooleanField(default=False, verbose_name='Confirmar de recibido')),
            ],
        ),
        migrations.CreateModel(
            name='DispositivosTriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(max_length=100)),
                ('identificador', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaHistoricoEmpresa', to='bodega.Empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaquinaPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('servicio_programado', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Servicio Programado')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaPerfilEncargado', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaPerfilMaquina', to='bodega.Maquina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaquinaProblema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarTriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('rando_inicia', models.PositiveSmallIntegerField()),
                ('rando_termina', models.PositiveSmallIntegerField()),
                ('a_inventario_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relRegistrarTriageInventarioEntrada', to='bodega.InventarioEntrada')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRegistrarTriageCreadoPor', to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relRegistrarTriageDispositivosTriage', to='bodega.DispositivosTriage')),
                ('no_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relRegistrarTriageControlTriage', to='bodega.ControlTriage')),
            ],
        ),
        migrations.CreateModel(
            name='TiposEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='maquinahistorico',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaHistoricoMaquinaPerfil', to='bodega.MaquinaPerfil'),
        ),
        migrations.AddField(
            model_name='maquinahistorico',
            name='tecnico_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaHistoricoTecnicoSupervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maquinahistorico',
            name='trabajo_realizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaHistoricoEmpresa', to='bodega.MaquinaProblema'),
        ),
        migrations.AddField(
            model_name='despachotriage',
            name='a_inventario_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relDespachoTriageInventarioEntrada', to='bodega.InventarioEntrada'),
        ),
        migrations.AddField(
            model_name='despachotriage',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relDespachoTriageDispositivosTriage', to='bodega.DispositivosTriage'),
        ),
        migrations.AddField(
            model_name='despachotriage',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDespachoTriageReimpresosEntrega', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despachotriage',
            name='no_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relDespachoTriageControlTriage', to='bodega.ControlTriage'),
        ),
        migrations.AddField(
            model_name='despachotriage',
            name='recibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relDespachoTriageReimpresosRecibe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controltriagereimpresos',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relControlTriageReimpresosDispositivosTriage', to='bodega.DispositivosTriage'),
        ),
        migrations.AddField(
            model_name='controltriagereimpresos',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relControlTriageReimpresosEntrega', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controltriagereimpresos',
            name='recibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relControlTriageReimpresosRecibe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controltriage',
            name='ingresa_como',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relControlTriageTiposEntrada', to='bodega.TiposEntrada'),
        ),
    ]
