# Generated by Django 2.0.2 on 2019-03-05 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('aspecto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aspectos_Evaluados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumple', models.BooleanField(default=False)),
                ('anotaciones', models.TextField(blank=True, max_length=250, null=True)),
                ('aspecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_AspectosEvaluados_Aspectos', to='equipamientos.Aspectos')),
            ],
        ),
        migrations.CreateModel(
            name='Cambio_Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('link_scan', models.URLField(blank=True, null=True)),
                ('triage_malo', models.CharField(blank=True, max_length=10, null=True)),
                ('falla', models.TextField(blank=True, max_length=150, null=True)),
                ('triage_bueno', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('entrega', models.PositiveSmallIntegerField()),
                ('udi', models.CharField(blank=True, max_length=150, null=True)),
                ('destino', models.CharField(blank=True, max_length=250, null=True)),
                ('latitud', models.CharField(blank=True, max_length=25, null=True)),
                ('longitud', models.CharField(blank=True, max_length=25, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Equipamiento_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inconvenientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_reporte', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('encargado_que_recibe', models.CharField(blank=True, max_length=100, null=True)),
                ('link_fotos', models.URLField(blank=True, null=True)),
                ('condiciones', models.TextField(blank=True, max_length=250, null=True)),
                ('recomendaciones', models.TextField(blank=True, max_length=250, null=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_resuelto', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('link_scan', models.URLField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Inconvenientes_User', to=settings.AUTH_USER_MODEL)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_Inconvenientes_Equipamiento', to='equipamientos.Equipamiento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto_Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado', models.BooleanField(default=False)),
                ('anotaciones', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('producto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Productos_Entregados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('link_scan', models.URLField(blank=True, null=True)),
                ('encargado_recibe', models.CharField(blank=True, max_length=100, null=True)),
                ('anotaciones', models.TextField(blank=True, max_length=250, null=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_ProductosEntregados_Equipamiento', to='equipamientos.Equipamiento')),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_ProductosEntregados_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productos_entregados',
            name='estrellas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_ProductosEntregados_Valoracion', to='equipamientos.Valoraciones'),
        ),
        migrations.AddField(
            model_name='producto_lista',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_ProductoLista_ProductosEntregados', to='equipamientos.Productos_Entregados'),
        ),
        migrations.AddField(
            model_name='producto_lista',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_ProductoLista_Productos', to='equipamientos.Productos'),
        ),
        migrations.AddField(
            model_name='cambio_equipo',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_CambioEquipo_Dispositivo', to='equipamientos.Dispositivo'),
        ),
        migrations.AddField(
            model_name='cambio_equipo',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_CambioEquipo_Equipamiento', to='equipamientos.Equipamiento'),
        ),
        migrations.AddField(
            model_name='cambio_equipo',
            name='hecho_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_CambioEquipo_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aspectos_evaluados',
            name='inconveniente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_AspectosEvaluados_Inconvenientes', to='equipamientos.Inconvenientes'),
        ),
    ]
