# Generated by Django 2.0.2 on 2019-03-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='entrega',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='udi',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
