# Generated by Django 2.0.2 on 2019-04-03 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamientos', '0002_auto_20190308_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='institucion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
