# Generated by Django 2.0.2 on 2019-04-09 20:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipamientos', '0003_auto_20190403_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_reporte', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('detalle_inconvenientes', models.TextField(blank=True, null=True)),
                ('informe_general', models.TextField(blank=True, null=True)),
                ('observacion_subjefe', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('inconvenientes', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInformeUser', to=settings.AUTH_USER_MODEL)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relInformeEquipamiento', to='equipamientos.Equipamiento')),
                ('subjefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInformeSubjefeUser', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInformeTecnicoUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
