# Generated by Django 2.0.2 on 2019-04-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamientos', '0004_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='cerrar_informe',
            field=models.BooleanField(default=False),
        ),
    ]
