# Generated by Django 2.0.2 on 2019-04-09 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipamientos', '0005_informe_cerrar_informe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='subjefe',
        ),
        migrations.AddField(
            model_name='informe',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInformeSupervisorUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
