# Generated by Django 2.0.2 on 2019-04-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamientos', '0006_auto_20190409_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='observacion_subjefe',
            new_name='observacion_supervisor',
        ),
    ]
