# Generated by Django 2.0.2 on 2019-01-23 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20190119_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignarEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('devolucion', models.BooleanField(default=False, verbose_name='Devolución')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoCargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='equipocargado',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_EquipoCargado_Area', to='registration.Area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='asignarequipo',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_AsignarEquipo_EquipoCargado', to='registration.EquipoCargado', verbose_name='Asignación'),
        ),
        migrations.AddField(
            model_name='asignarequipo',
            name='devuelve',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_AsignarEquipo_User', to=settings.AUTH_USER_MODEL, verbose_name='Quién devuelve'),
        ),
        migrations.AddField(
            model_name='asignarequipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_AsignarEquipo_TipoEquipo', to='registration.TipoEquipo', verbose_name='Tipo de Equipo'),
        ),
    ]
