# Generated by Django 2.0.2 on 2019-01-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190123_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignarequipo',
            name='cantidad',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
