# Generated by Django 2.0.2 on 2019-01-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190123_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='correo',
        ),
    ]
