# Generated by Django 2.0.2 on 2019-01-23 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_perfil_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocargado',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rel_EquipoCargado_Area', to='registration.Area', verbose_name='Área'),
        ),
    ]
