# Generated by Django 2.0.2 on 2019-05-28 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('movimiento', models.IntegerField()),
                ('desecho', models.BooleanField(default=False)),
                ('bodeguita', models.BooleanField(default=False)),
                ('dispositivo', models.CharField(max_length=100)),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('creado_en_suni', models.BooleanField(default=False)),
                ('hoja_impresa', models.BooleanField(default=False)),
                ('genera_kardex', models.BooleanField(default=False)),
                ('kardex', models.IntegerField()),
                ('registro_en_correo', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('supervision_completada', models.BooleanField(default=False)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relMovimientoUsuarioEntrega', to=settings.AUTH_USER_MODEL)),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relMovimientoUsuarioRecibe', to=settings.AUTH_USER_MODEL)),
                ('supervisado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relMovimientoUsuarioSupervisa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relMovimientoTipo', to='supervision.TipoMovimiento'),
        ),
    ]
