# Generated by Django 2.0.2 on 2019-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='bodeguita',
            field=models.BooleanField(default=False, verbose_name='Afecta Kardex'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='kardex',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. Kardex'),
        ),
    ]
