# Generated by Django 2.0.2 on 2019-06-05 19:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervision', '0002_auto_20190528_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDepuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('dispositivo', models.CharField(max_length=100)),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('entrada', models.IntegerField()),
                ('fecha_entrega', models.DateField(default=datetime.datetime.now)),
                ('creado_en_suni', models.BooleanField(default=False)),
                ('hoja_impresa', models.BooleanField(default=False)),
                ('kardex', models.IntegerField(blank=True, null=True, verbose_name='No. Kardex')),
                ('registro_en_correo', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cerrar', models.BooleanField(default=False)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relEntradaUsuarioEntrega', to=settings.AUTH_USER_MODEL)),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relEntradaUsuarioRecibe', to=settings.AUTH_USER_MODEL)),
                ('supervisado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relEntradaUsuarioSupervisa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='bodeguita',
        ),
        migrations.AddField(
            model_name='detalledepuracion',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relDepuracionEntrada', to='supervision.Entrada'),
        ),
    ]
