# Generated by Django 2.0.2 on 2019-06-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0003_auto_20190605_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='fecha_entrega',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='detalledepuracion',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='detalledepuracion',
            name='creado',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='entrada',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
